# This is a basic workflow to help you get started with Actions

name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

      - name: step2
        run: 
          echo "github.action_path" ${{ github.action_path }}
          echo "github.action_ref" ${{ github.action_ref }}
          echo "github.action" ${{ github.action }}
          echo "github.action_repository" ${{ github.action_repository }}
