# This is a basic workflow to help you get started with Actions

name: hello-world
on:
  push:
    branches:
      - master
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: pull_request closed
        run: echo pull_request closed teste


