# This is a basic workflow to help you get started with Actions

name: hello-world
on: pull_request
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo no pull_request

      - name: step2
        run: 
          echo github.action_path $GITHUB_ACTION_PATH
          github.workspace $GITHUB_WORKSPACE
          github.event_name $GITHUB_EVENT_NAME
          github.branch $GITHUB_BRANCH
